// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiihplbdqruwijykzxqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpaWhwbGJkcXJ1d2lqeWt6eHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjI4OTIsImV4cCI6MjA2MDgzODg5Mn0.yBkiCr_MN5bkbRrlrsjb8AGYA-U20flaMW1jA4NjMUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);